name: 'Terraform Apply'

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      env:
        LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
