name: 'Terraform Plan'

on:
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      env:
        LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      env:
        LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
